
use mcrdb;



-- ---
-- Globals
-- ---

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;

-- ---
-- Table 'ACAO_LOG'
-- INCLUIR/ALTERAR/DESATIVAR
-- ---

DROP TABLE IF EXISTS `ACAO_LOG`;

CREATE TABLE `ACAO_LOG` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) COMMENT='INCLUIR/ALTERAR/DESATIVAR';

-- ---
-- Table 'CLINICA'
--
-- ---

DROP TABLE IF EXISTS `CLINICA`;

CREATE TABLE `CLINICA` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome_fantasia` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  `cnpj` VARCHAR(17) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `ativo` BOOLEAN NOT NULL DEFAULT true,
  `razao_social` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'CLINICA_CONVENIO'
--
-- ---

DROP TABLE IF EXISTS `CLINICA_CONVENIO`;

CREATE TABLE `CLINICA_CONVENIO` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_clinica` INTEGER NOT NULL,
  `id_convenio` INTEGER NOT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'CLINICA_MEDICOS'
--
-- ---

DROP TABLE IF EXISTS `CLINICA_MEDICOS`;

CREATE TABLE `CLINICA_MEDICOS` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_clinica` INTEGER NOT NULL,
  `id_medico` INTEGER NOT NULL,
  `principal` BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'CONVENIO'
--
-- ---

DROP TABLE IF EXISTS `CONVENIO`;

CREATE TABLE `CONVENIO` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `ativo` BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'ENDERECO'
--
-- ---

DROP TABLE IF EXISTS `ENDERECO`;

CREATE TABLE `ENDERECO` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(150) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'ENDERECO_CLINICA'
--
-- ---

DROP TABLE IF EXISTS `ENDERECO_CLINICA`;

CREATE TABLE `ENDERECO_CLINICA` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_endereco` INTEGER NOT NULL,
  `id_clinicia` INTEGER NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'ENDERECO_CONVENIO'
--
-- ---

DROP TABLE IF EXISTS `ENDERECO_CONVENIO`;

CREATE TABLE `ENDERECO_CONVENIO` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_endereco` INTEGER NOT NULL,
  `id_convenio` INTEGER NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'ENDERECO_PESSOA'
--
-- ---

DROP TABLE IF EXISTS `ENDERECO_PESSOA`;

CREATE TABLE `ENDERECO_PESSOA` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_endereco` INTEGER NOT NULL,
  `id_pessoa` INTEGER NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'FATURAMENTO'
--
-- ---

DROP TABLE IF EXISTS `FATURAMENTO`;

CREATE TABLE `FATURAMENTO` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_status` INTEGER NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `data_fechamento` DATETIME NULL DEFAULT NULL,
  `id_clinica` INTEGER NOT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'FATURAMENTO_PREVIA'
--
-- ---

DROP TABLE IF EXISTS `FATURAMENTO_PREVIA`;

CREATE TABLE `FATURAMENTO_PREVIA` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_faturamento` INTEGER NOT NULL,
  `id_previa` INTEGER NOT NULL,
  `status` BOOLEAN NOT NULL DEFAULT false,
  `data_pgto` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'LOGGING'
--
-- ---

DROP TABLE IF EXISTS `LOGGING`;

CREATE TABLE `LOGGING` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_usuario` INTEGER NOT NULL,
  `id_acao` INTEGER NOT NULL,
  `data` DATETIME NOT NULL,
  `id_tabela` INTEGER NOT NULL,
  `id_registro` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'PERFIL'
--
-- ---

DROP TABLE IF EXISTS `PERFIL`;

CREATE TABLE `PERFIL` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'PESSOA'
--
-- ---

DROP TABLE IF EXISTS `PESSOA`;

CREATE TABLE `PESSOA` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_tipo_pessoa` INTEGER NOT NULL,
  `id_usuario` INTEGER NULL DEFAULT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(100) NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `crm` VARCHAR(100) NULL DEFAULT NULL,
  `ativo` BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'PESSOA_PLANO'
--
-- ---

DROP TABLE IF EXISTS `PESSOA_PLANO`;

CREATE TABLE `PESSOA_PLANO` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_plano` INTEGER NOT NULL,
  `id_pessoa` INTEGER NOT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'PLANO'
--
-- ---

DROP TABLE IF EXISTS `PLANO`;

CREATE TABLE `PLANO` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(200) NULL DEFAULT NULL,
  `id_convenio` INTEGER NOT NULL,
  `ativo` BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'PLANO_PRODUTO'
--
-- ---

DROP TABLE IF EXISTS `PLANO_PRODUTO`;

CREATE TABLE `PLANO_PRODUTO` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_plano` INTEGER NOT NULL,
  `id_produto` INTEGER NOT NULL,
  `ativo` BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'PREVIA'
--
-- ---

DROP TABLE IF EXISTS `PREVIA`;

CREATE TABLE `PREVIA` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_tipo_previa` INTEGER NOT NULL,
  `id_clinica` INTEGER NOT NULL,
  `id_pessoa` INTEGER NOT NULL,
  `id_convenio` INTEGER NOT NULL,
  `id_status` INTEGER NOT NULL,
  `data` DATETIME NOT NULL,
  `observacao` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'PREVIA_PRODUTOS'
--
-- ---

DROP TABLE IF EXISTS `PREVIA_PRODUTOS`;

CREATE TABLE `PREVIA_PRODUTOS` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_produtos` INTEGER NOT NULL,
  `id_previa` INTEGER NOT NULL,
  `valor` DOUBLE NOT NULL,
  `observacao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'PRODUTOS'
--
-- ---

DROP TABLE IF EXISTS `PRODUTOS`;

CREATE TABLE `PRODUTOS` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `codigo_amb` VARCHAR(20) NULL DEFAULT NULL,
  `codigo_tus` VARCHAR(20) NULL DEFAULT NULL,
  `descricao` VARCHAR(150) NOT NULL,
  `qtd_ch` INTEGER NULL DEFAULT NULL,
  `porte` INTEGER NULL DEFAULT NULL,
  `porte_ch` INTEGER NULL DEFAULT NULL,
  `m2_filme` DOUBLE NULL DEFAULT NULL,
  `ativo` BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'STATUS_FATURAMENTO'
--
-- ---

DROP TABLE IF EXISTS `STATUS_FATURAMENTO`;

CREATE TABLE `STATUS_FATURAMENTO` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'STATUS_PREVIA'
--
-- ---

DROP TABLE IF EXISTS `STATUS_PREVIA`;

CREATE TABLE `STATUS_PREVIA` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'TABELA_LOG'
-- Nome da TABELA (Para agilizar o desenvolvimento) ->
-- Cadastro de clientes (1);
-- Cadastro de pacientes e prévias (2);
-- Cadastro de convênios e tabelas (3);
-- Módulo de faturamento
-- ---

DROP TABLE IF EXISTS `TABELA_LOG`;

CREATE TABLE `TABELA_LOG` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) COMMENT='Nome da TABELA (Para agilizar o desenvolvimento) ->
Cadastro';

-- ---
-- Table 'TIPO_TELEFONE'
--
-- ---

DROP TABLE IF EXISTS `TIPO_TELEFONE`;

CREATE TABLE `mcrdb`.`TIPO_TELEFONE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NULL),
    PRIMARY KEY (`id`));



-- ---
-- Table 'TELEFONE'
--
-- ---

DROP TABLE IF EXISTS `TELEFONE`;

CREATE TABLE `TELEFONE` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(9) NOT NULL,
  `ddd` VARCHAR(2) NOT NULL,
  `id_tipo_telefone` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `id_idx` (`id_tipo_telefone`),
  CONSTRAINT `id` FOREIGN KEY (`id_tipo_telefone`) REFERENCES `tipo_telefone` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ---
-- Table 'TELEFONE_CLINICA'
--
-- ---

DROP TABLE IF EXISTS `TELEFONE_CLINICA`;

CREATE TABLE `TELEFONE_CLINICA` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_telefone` INTEGER NOT NULL,
  `id_clinica` INTEGER NOT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'TELEFONE_CONVENIO'
--
-- ---

DROP TABLE IF EXISTS `TELEFONE_CONVENIO`;

CREATE TABLE `TELEFONE_CONVENIO` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_telefone` INTEGER NOT NULL,
  `id_convenio` INTEGER NOT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'TELEFONE_PESSOA'
--
-- ---

DROP TABLE IF EXISTS `TELEFONE_PESSOA`;

CREATE TABLE `TELEFONE_PESSOA` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `id_pessoa` INTEGER NOT NULL,
  `id_telefone` INTEGER NOT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'TIPO_PESSOA'
-- Funcionário/Paciente/Médico
-- ---

DROP TABLE IF EXISTS `TIPO_PESSOA`;

CREATE TABLE `TIPO_PESSOA` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) COMMENT='Funcionário/Paciente/Médico';

-- ---
-- Table 'TIPO_PREVIA'
--
-- ---

DROP TABLE IF EXISTS `TIPO_PREVIA`;

CREATE TABLE `TIPO_PREVIA` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'USUARIO'
--
-- ---

DROP TABLE IF EXISTS `USUARIO`;

CREATE TABLE `USUARIO` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(20) NULL DEFAULT NULL,
  `ativo` BOOLEAN NOT NULL DEFAULT true,
  `id_perfil` INTEGER NOT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Foreign Keys
-- ---

ALTER TABLE `CLINICA_CONVENIO` ADD FOREIGN KEY (id_clinica) REFERENCES `CLINICA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `CLINICA_CONVENIO` ADD FOREIGN KEY (id_convenio) REFERENCES `CONVENIO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `CLINICA_MEDICOS` ADD FOREIGN KEY (id_clinica) REFERENCES `CLINICA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `CLINICA_MEDICOS` ADD FOREIGN KEY (id_medico) REFERENCES `PESSOA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `ENDERECO_CLINICA` ADD FOREIGN KEY (id_endereco) REFERENCES `ENDERECO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `ENDERECO_CLINICA` ADD FOREIGN KEY (id_clinicia) REFERENCES `CLINICA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `ENDERECO_CONVENIO` ADD FOREIGN KEY (id_endereco) REFERENCES `ENDERECO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `ENDERECO_CONVENIO` ADD FOREIGN KEY (id_convenio) REFERENCES `CONVENIO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `ENDERECO_PESSOA` ADD FOREIGN KEY (id_endereco) REFERENCES `ENDERECO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `ENDERECO_PESSOA` ADD FOREIGN KEY (id_pessoa) REFERENCES `PESSOA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `FATURAMENTO` ADD FOREIGN KEY (id_status) REFERENCES `STATUS_FATURAMENTO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `FATURAMENTO` ADD FOREIGN KEY (id_clinica) REFERENCES `CLINICA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `FATURAMENTO_PREVIA` ADD FOREIGN KEY (id_faturamento) REFERENCES `FATURAMENTO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `FATURAMENTO_PREVIA` ADD FOREIGN KEY (id_previa) REFERENCES `PREVIA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `LOGGING` ADD FOREIGN KEY (id_usuario) REFERENCES `USUARIO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `LOGGING` ADD FOREIGN KEY (id_acao) REFERENCES `ACAO_LOG` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `LOGGING` ADD FOREIGN KEY (id_tabela) REFERENCES `TABELA_LOG` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PESSOA` ADD FOREIGN KEY (id_tipo_pessoa) REFERENCES `TIPO_PESSOA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PESSOA` ADD FOREIGN KEY (id_usuario) REFERENCES `USUARIO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PESSOA_PLANO` ADD FOREIGN KEY (id_plano) REFERENCES `PLANO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PESSOA_PLANO` ADD FOREIGN KEY (id_pessoa) REFERENCES `PESSOA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PLANO` ADD FOREIGN KEY (id_convenio) REFERENCES `CONVENIO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PLANO_PRODUTO` ADD FOREIGN KEY (id_plano) REFERENCES `PLANO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PLANO_PRODUTO` ADD FOREIGN KEY (id_produto) REFERENCES `PRODUTOS` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PREVIA` ADD FOREIGN KEY (id_tipo_previa) REFERENCES `TIPO_PREVIA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PREVIA` ADD FOREIGN KEY (id_clinica) REFERENCES `CLINICA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PREVIA` ADD FOREIGN KEY (id_pessoa) REFERENCES `PESSOA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PREVIA` ADD FOREIGN KEY (id_convenio) REFERENCES `CONVENIO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PREVIA` ADD FOREIGN KEY (id_status) REFERENCES `STATUS_PREVIA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PREVIA_PRODUTOS` ADD FOREIGN KEY (id_produtos) REFERENCES `PRODUTOS` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `PREVIA_PRODUTOS` ADD FOREIGN KEY (id_previa) REFERENCES `PREVIA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `TELEFONE_CLINICA` ADD FOREIGN KEY (id_telefone) REFERENCES `TELEFONE` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `TELEFONE_CLINICA` ADD FOREIGN KEY (id_clinica) REFERENCES `CLINICA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `TELEFONE_CONVENIO` ADD FOREIGN KEY (id_telefone) REFERENCES `TELEFONE` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `TELEFONE_CONVENIO` ADD FOREIGN KEY (id_convenio) REFERENCES `CONVENIO` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `TELEFONE_PESSOA` ADD FOREIGN KEY (id_pessoa) REFERENCES `PESSOA` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `TELEFONE_PESSOA` ADD FOREIGN KEY (id_telefone) REFERENCES `TELEFONE` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `USUARIO` ADD FOREIGN KEY (id_perfil) REFERENCES `PERFIL` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;

-- ---
-- Table Properties
-- ---

-- ALTER TABLE `ACAO_LOG` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `CLINICA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `CLINICA_CONVENIO` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `CLINICA_MEDICOS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `CONVENIO` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `ENDERECO` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `ENDERECO_CLINICA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `ENDERECO_CONVENIO` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `ENDERECO_PESSOA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `FATURAMENTO` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `FATURAMENTO_PREVIA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `LOGGING` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PERFIL` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PESSOA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PESSOA_PLANO` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PLANO` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PLANO_PRODUTO` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PREVIA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PREVIA_PRODUTOS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PRODUTOS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `STATUS_FATURAMENTO` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `STATUS_PREVIA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `TABELA_LOG` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `TELEFONE` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `TELEFONE_CLINICA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `TELEFONE_CONVENIO` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `TELEFONE_PESSOA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `TIPO_PESSOA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `TIPO_PREVIA` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `USUARIO` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
